# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hex_in = QtWidgets.QLineEdit(self.centralwidget)
        self.hex_in.setGeometry(QtCore.QRect(123, 100, 71, 20))
        self.hex_in.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.hex_in.setFont(font)
        self.hex_in.setStyleSheet("border: 0;\n"
"background-color: rgb(255, 255, 255);")
        self.hex_in.setMaxLength(6)
        self.hex_in.setObjectName("hex_in")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 100, 15, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 83, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 145, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.rgb_in_G = QtWidgets.QSpinBox(self.centralwidget)
        self.rgb_in_G.setGeometry(QtCore.QRect(130, 160, 50, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.rgb_in_G.setFont(font)
        self.rgb_in_G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rgb_in_G.setMaximum(255)
        self.rgb_in_G.setProperty("value", 255)
        self.rgb_in_G.setObjectName("rgb_in_G")
        self.rgb_in_B = QtWidgets.QSpinBox(self.centralwidget)
        self.rgb_in_B.setGeometry(QtCore.QRect(180, 160, 50, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.rgb_in_B.setFont(font)
        self.rgb_in_B.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rgb_in_B.setMaximum(255)
        self.rgb_in_B.setProperty("value", 255)
        self.rgb_in_B.setObjectName("rgb_in_B")
        self.rgb_in_R = QtWidgets.QSpinBox(self.centralwidget)
        self.rgb_in_R.setGeometry(QtCore.QRect(80, 160, 50, 22))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.rgb_in_R.setFont(font)
        self.rgb_in_R.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.rgb_in_R.setMaximum(255)
        self.rgb_in_R.setProperty("value", 255)
        self.rgb_in_R.setObjectName("rgb_in_R")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.hex_in.setText(_translate("MainWindow", "FFFFFF"))
        self.label.setText(_translate("MainWindow", "#"))
        self.label_2.setText(_translate("MainWindow", "HEX:"))
        self.label_3.setText(_translate("MainWindow", "RGB:"))
